services:
  - type: web
    name: super-alpha
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
      - key: OPENROUTER_API_KEY
        value: your_openrouter_api_key_here